### ISSUE TITLE
Database structure for characters / game admin

### ISSUE THREAD

**Issue by kacpak** [kacpak/rpg-helper#24]
[pl]
@MrocznyMarcel co sądzisz o strukturze?
![baza](https://cloud.githubusercontent.com/assets/2863205/26824391/845e9be2-4ab1-11e7-8246-851b4ac16dc1.jpg)

W tej chwili 1 user może mieć tylko 1 rolę w sesji - gracz lub mistrz gry.  
Wydaje mi się że mistrz gry nie potrzebuje dodatkowych informacji w bazie, więc uznałem że w join table dla user/session/character bycie mistrzem gry to flaga - True/False.  
Masz coś do dodania? Wskazówki? Co można jeszcze dodać albo o czym pomyśleć?

**Comment by kacpak** [comment]
![diagram zwiazkow encji](https://user-images.githubusercontent.com/2863205/26892650-4548909e-4bb9-11e7-8cc7-bdc286c9fecb.png)

**Comment by MrocznyMarcel** [comment]
Wszystko wydaje się tip top. W tej chwili też nie uważam, aby MG potrzebował dodatkowych danych. A jeśli w przyszłości będzie trzeba, to można zawsze dodać tabelę.
Aczkolwiek w przyszłości możemy też pomyśleć o zaimplementowaniu jakiejś NoSQLowej bazy danych.

**Comment by kacpak** [comment]
Zobaczmy w jakim kierunku pójdzie aplikacja :-)
